#!/bin/bash

cd ~;
echo -e "Simple icon pack changer for ArcoLinux by prpl.

The best way to fix something is by searching your filesystem
for hours and then just replacing the icon pack itself. :)"

cd /usr/share/icons;
ls /usr/share/icons;
read "Select icon pack." ASK;
sudo rm -R /usr/share/icons/arcolinux-candy-beauty;
sudo mv $ASK /usr/share/icons/arcolinux-candy-beauty;
sudo cp -R /usr/share/icons/arcolinux-candy-beauty $ASK;