#!/bin/bash

B="\e[0;34;40m"
R="\e[0m"

cd ~/.scripts/dotwtf;

if [[ $1 ]]; then echo -e "$B→ Attempting to redirect '$1'.$R"; fi;

# WALLPAPER
if [[ $1 == "-w" ]]; then
    sudo bash .scripts/dotwtf/misc/wallpaper.sh $2;
    exit 1;
fi;

echo -e "\n"$B"prplwtf/dotfiles - dotwtf"$R"
  -w    change wallpaper""\n";
